pool:
  vmImage: 'Ubuntu 16.04'

variables:
  # nginxBuildDirectory: 'nginx-fpm/0.4/'
  nginxBuildDirectory: 'nginx-fpm/php7.2.11'
  nginxImageName: 'custmom-nginx-fpm'

steps:


- task: Docker@2
  displayName: 'Login to Azure Container Registry'
  inputs:
    command: login
    containerRegistry: 'jabecreg.azurecr.io'
    
- task: Docker@2
  displayName: 'Build nginx image'
  inputs:
   repository: 'jabecreg.azurecr.io/$(nginxImageName)'
   command: buildAndPush
   dockerFile: '$(nginxBuildDirectory)/Dockerfile'
   buildContext: '$(nginxBuildDirectory)'