# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  nginxSourceFolder: 'nginx-fpm/0.4/'
  nginxImageName: 'nginx-fpm:$(build.buildId)'

steps:
#- task: CopyFiles@2
#  displayName: 'Copy nginx Dockerfiles to: $(build.sourcesdirectory)'
#  inputs:
#    SourceFolder: '$(nginxSourceFolder)'
#    Contents: '*'
#    TargetFolder: '$(build.sourcesdirectory)'
#- script: docker build -f Dockerfile -t $(nginxImageName) .
#  displayName: 'nginx docker build'
- task: Docker@1
  displayName: 'Build nginx image'
  inputs:
    azureSubscriptionEndpoint: 'Azure CXP FTA Internal Subscription JABEC (e6c0a81f-8120-4f31-9d5e-7f3c5ee4a142)'
    azureContainerRegistry: jabecreg.azurecr.io
    imageName: 'jabecreg.azurecr.io/$(nginxImageName)'
    #buildContext: '$(nginxSourceFolder)'
    dockerFile: '$(nginxSourceFolder)/Dockerfile'
    useDefaultContext: true
  
#- task: Docker@1
#  displayName: 'Push nginx image'
#  inputs:
#    command: 'Push an Image'
#    imageName: 'jabecreg.azurecr.io/$(nginxImageName)'
#    includeLatestTag: true

#- task: Docker@1
#  displayName: Login
#  inputs:
#    azureSubscriptionEndpoint: 'Azure CXP FTA Internal Subscription JABEC (e6c0a81f-8120-4f31-9d5e-7f3c5ee4a142)'
#    azureContainerRegistry: jabecreg.azurecr.io
#    command: login
