# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'your-container-image-name:$(build.buildId)'
  nginxSourceFolder: 'nginx-fpm/0.4/'
  nginxImageName: 'nginx-fpm:$(build.buildId)'
  wordpressDockerfilePath: 'wordpress-alpine-php/0.61/Dockerfile' 

steps:
- task: CopyFiles@2
  displayName: 'Copy nginx Dockerfiles to: $(build.sourcesdirectory)'
  inputs:
    SourceFolder: '$(nginxSourceFolder)'
    Contents: '*'
    TargetFolder: '$(build.sourcesdirectory)'

#- script: docker build -f Dockerfile -t $(nginxImageName) .
#  displayName: 'nginx docker build'

- task: Docker@1
  displayName: 'Build nginx image'
  inputs:
    imageName: 'jabecreg.azurecr.io/$(nginxImageName)'
    dockerFile: 'Dockerfile'
- task: Docker@1
  displayName: Login
  inputs:
    azureSubscriptionEndpoint: 'Azure CXP FTA Internal Subscription JABEC'
    azureContainerRegistry: jabecreg.azurecr.io
    command: login
- task: Docker@1
  displayName: 'Push nginx image'
  inputs:
    command: 'Push an Image'
    imageName: 'jabecreg.azurecr.io/$(nginxImageName)'
    includeLatestTag: true

    
