pool:
  vmImage: 'Ubuntu 16.04'

variables:
  nginxBuildDirectory: 'nginx-fpm/php7.2.11'

steps:


- task: Docker@2
  displayName: 'Login to Azure Container Registry'
  inputs:
    command: login
    containerRegistry: 'jabecreg.azurecr.io'
    
- task: Docker@2
  displayName: 'Build nginx image'
  inputs:
   repository: 'custom-nginx-fpm'
   command: buildAndPush
   dockerFile: '$(nginxBuildDirectory)/Dockerfile'
   buildContext: '$(nginxBuildDirectory)'