pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildDirectory: 'nginx-fpm/0.4/'
  nginxImageName: 'nginx-fpm:$(build.buildId)'

steps:
- task: Docker@1
  displayName: 'Build nginx image'
  inputs:
    imageName: 'jabecreg.azurecr.io/$(nginxImageName)'
    dockerFile: '$(buildDirectory)/Dockerfile'
    useDefaultContext: true
  
- task: Docker@1
  displayName: 'Login to Azure Container Registry'
  inputs:
    command: login
    azureSubscriptionEndpoint: 'Azure CXP FTA Internal Subscription JABEC (e6c0a81f-8120-4f31-9d5e-7f3c5ee4a142)'
    azureContainerRegistry: jabecreg.azurecr.io

- task: Docker@1
  displayName: 'Push nginx image to Azure Container Registry'
  inputs:
    command: 'Push an Image'
    imageName: 'jabecreg.azurecr.io/$(nginxImageName)'
    includeLatestTag: true